// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyApi.Models.Database;

namespace MyApi.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20210820195119_AddSeedAnimals")]
    partial class AddSeedAnimals
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("Value")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("MyApi.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Breed")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Type")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            Age = 14,
                            Breed = "beagle",
                            Description = "cute and affectionate",
                            Name = "ames",
                            Type = "dog"
                        },
                        new
                        {
                            AnimalId = 2,
                            Age = 8,
                            Breed = "norweigan",
                            Description = "loves to run and play",
                            Name = "quin",
                            Type = "cat"
                        },
                        new
                        {
                            AnimalId = 3,
                            Age = 7,
                            Breed = "husky",
                            Description = "needs a quiet home",
                            Name = "poppy",
                            Type = "dog"
                        },
                        new
                        {
                            AnimalId = 4,
                            Age = 6,
                            Breed = "poodle",
                            Description = "needs a quiet home",
                            Name = "frederick",
                            Type = "dog"
                        },
                        new
                        {
                            AnimalId = 5,
                            Age = 16,
                            Breed = "poodle",
                            Description = "has a strong personality",
                            Name = "bob",
                            Type = "dog"
                        },
                        new
                        {
                            AnimalId = 6,
                            Age = 11,
                            Breed = "siberian",
                            Description = "cute and affectionate",
                            Name = "eric",
                            Type = "cat"
                        },
                        new
                        {
                            AnimalId = 7,
                            Age = 11,
                            Breed = "shorthair",
                            Description = "loves to run and play",
                            Name = "paws",
                            Type = "cat"
                        },
                        new
                        {
                            AnimalId = 8,
                            Age = 8,
                            Breed = "shorthair",
                            Description = "loves to run and play",
                            Name = "hal",
                            Type = "cat"
                        },
                        new
                        {
                            AnimalId = 9,
                            Age = 2,
                            Breed = "munchkin",
                            Description = "loves to run and play",
                            Name = "whiskers",
                            Type = "cat"
                        },
                        new
                        {
                            AnimalId = 10,
                            Age = 17,
                            Breed = "beagle",
                            Description = "loves to run and play",
                            Name = "thor",
                            Type = "dog"
                        },
                        new
                        {
                            AnimalId = 11,
                            Age = 19,
                            Breed = "german shepherd",
                            Description = "has a strong personality",
                            Name = "hal",
                            Type = "dog"
                        },
                        new
                        {
                            AnimalId = 12,
                            Age = 8,
                            Breed = "shorthair",
                            Description = "curious about the world",
                            Name = "hailey",
                            Type = "cat"
                        },
                        new
                        {
                            AnimalId = 13,
                            Age = 4,
                            Breed = "poodle",
                            Description = "cute and affectionate",
                            Name = "fig",
                            Type = "dog"
                        },
                        new
                        {
                            AnimalId = 14,
                            Age = 1,
                            Breed = "siberian",
                            Description = "has a strong personality",
                            Name = "yarin",
                            Type = "cat"
                        },
                        new
                        {
                            AnimalId = 15,
                            Age = 3,
                            Breed = "shorthair",
                            Description = "loves to run and play",
                            Name = "thor",
                            Type = "cat"
                        },
                        new
                        {
                            AnimalId = 16,
                            Age = 18,
                            Breed = "siberian",
                            Description = "has a strong personality",
                            Name = "hailey",
                            Type = "cat"
                        },
                        new
                        {
                            AnimalId = 17,
                            Age = 1,
                            Breed = "lab",
                            Description = "cute and affectionate",
                            Name = "frederick",
                            Type = "dog"
                        },
                        new
                        {
                            AnimalId = 18,
                            Age = 8,
                            Breed = "poodle",
                            Description = "loves to run and play",
                            Name = "bob",
                            Type = "dog"
                        },
                        new
                        {
                            AnimalId = 19,
                            Age = 17,
                            Breed = "lab",
                            Description = "curious about the world",
                            Name = "whiskers",
                            Type = "dog"
                        },
                        new
                        {
                            AnimalId = 20,
                            Age = 15,
                            Breed = "shorthair",
                            Description = "has a strong personality",
                            Name = "eric",
                            Type = "cat"
                        },
                        new
                        {
                            AnimalId = 21,
                            Age = 9,
                            Breed = "norweigan",
                            Description = "loves to run and play",
                            Name = "frederick",
                            Type = "cat"
                        },
                        new
                        {
                            AnimalId = 22,
                            Age = 12,
                            Breed = "norweigan",
                            Description = "curious about the world",
                            Name = "ames",
                            Type = "cat"
                        },
                        new
                        {
                            AnimalId = 23,
                            Age = 14,
                            Breed = "lab",
                            Description = "has a strong personality",
                            Name = "fig",
                            Type = "dog"
                        },
                        new
                        {
                            AnimalId = 24,
                            Age = 7,
                            Breed = "german shepherd",
                            Description = "cute and affectionate",
                            Name = "thor",
                            Type = "dog"
                        },
                        new
                        {
                            AnimalId = 25,
                            Age = 2,
                            Breed = "german shepherd",
                            Description = "cute and affectionate",
                            Name = "eric",
                            Type = "dog"
                        },
                        new
                        {
                            AnimalId = 26,
                            Age = 14,
                            Breed = "munchkin",
                            Description = "loves to run and play",
                            Name = "poppy",
                            Type = "cat"
                        },
                        new
                        {
                            AnimalId = 27,
                            Age = 9,
                            Breed = "siberian",
                            Description = "loves to run and play",
                            Name = "yarin",
                            Type = "cat"
                        },
                        new
                        {
                            AnimalId = 28,
                            Age = 13,
                            Breed = "beagle",
                            Description = "loves to run and play",
                            Name = "thor",
                            Type = "dog"
                        },
                        new
                        {
                            AnimalId = 29,
                            Age = 15,
                            Breed = "norweigan",
                            Description = "cute and affectionate",
                            Name = "yarin",
                            Type = "cat"
                        },
                        new
                        {
                            AnimalId = 30,
                            Age = 3,
                            Breed = "munchkin",
                            Description = "has a strong personality",
                            Name = "pancake",
                            Type = "cat"
                        },
                        new
                        {
                            AnimalId = 31,
                            Age = 3,
                            Breed = "norweigan",
                            Description = "curious about the world",
                            Name = "yarin",
                            Type = "cat"
                        },
                        new
                        {
                            AnimalId = 32,
                            Age = 1,
                            Breed = "norweigan",
                            Description = "has a strong personality",
                            Name = "henry",
                            Type = "cat"
                        },
                        new
                        {
                            AnimalId = 33,
                            Age = 12,
                            Breed = "munchkin",
                            Description = "loves to run and play",
                            Name = "whiskers",
                            Type = "cat"
                        },
                        new
                        {
                            AnimalId = 34,
                            Age = 16,
                            Breed = "munchkin",
                            Description = "needs a quiet home",
                            Name = "james",
                            Type = "cat"
                        },
                        new
                        {
                            AnimalId = 35,
                            Age = 3,
                            Breed = "norweigan",
                            Description = "has a strong personality",
                            Name = "ames",
                            Type = "cat"
                        },
                        new
                        {
                            AnimalId = 36,
                            Age = 1,
                            Breed = "beagle",
                            Description = "curious about the world",
                            Name = "quin",
                            Type = "dog"
                        },
                        new
                        {
                            AnimalId = 37,
                            Age = 11,
                            Breed = "shorthair",
                            Description = "has a strong personality",
                            Name = "ames",
                            Type = "cat"
                        },
                        new
                        {
                            AnimalId = 38,
                            Age = 5,
                            Breed = "norweigan",
                            Description = "loves to run and play",
                            Name = "hal",
                            Type = "cat"
                        },
                        new
                        {
                            AnimalId = 39,
                            Age = 8,
                            Breed = "shorthair",
                            Description = "loves to run and play",
                            Name = "james",
                            Type = "cat"
                        },
                        new
                        {
                            AnimalId = 40,
                            Age = 13,
                            Breed = "siberian",
                            Description = "has a strong personality",
                            Name = "bob",
                            Type = "cat"
                        },
                        new
                        {
                            AnimalId = 41,
                            Age = 19,
                            Breed = "husky",
                            Description = "loves to run and play",
                            Name = "yarin",
                            Type = "dog"
                        },
                        new
                        {
                            AnimalId = 42,
                            Age = 5,
                            Breed = "norweigan",
                            Description = "cute and affectionate",
                            Name = "frederick",
                            Type = "cat"
                        },
                        new
                        {
                            AnimalId = 43,
                            Age = 14,
                            Breed = "lab",
                            Description = "has a strong personality",
                            Name = "eric",
                            Type = "dog"
                        },
                        new
                        {
                            AnimalId = 44,
                            Age = 4,
                            Breed = "shorthair",
                            Description = "cute and affectionate",
                            Name = "paws",
                            Type = "cat"
                        },
                        new
                        {
                            AnimalId = 45,
                            Age = 13,
                            Breed = "norweigan",
                            Description = "loves to run and play",
                            Name = "claire",
                            Type = "cat"
                        },
                        new
                        {
                            AnimalId = 46,
                            Age = 2,
                            Breed = "beagle",
                            Description = "cute and affectionate",
                            Name = "henry",
                            Type = "dog"
                        },
                        new
                        {
                            AnimalId = 47,
                            Age = 2,
                            Breed = "shorthair",
                            Description = "has a strong personality",
                            Name = "hailey",
                            Type = "cat"
                        },
                        new
                        {
                            AnimalId = 48,
                            Age = 3,
                            Breed = "siberian",
                            Description = "loves to run and play",
                            Name = "henry",
                            Type = "cat"
                        },
                        new
                        {
                            AnimalId = 49,
                            Age = 11,
                            Breed = "beagle",
                            Description = "has a strong personality",
                            Name = "claire",
                            Type = "dog"
                        },
                        new
                        {
                            AnimalId = 50,
                            Age = 6,
                            Breed = "shorthair",
                            Description = "cute and affectionate",
                            Name = "poppy",
                            Type = "cat"
                        },
                        new
                        {
                            AnimalId = 51,
                            Age = 5,
                            Breed = "lab",
                            Description = "curious about the world",
                            Name = "james",
                            Type = "dog"
                        },
                        new
                        {
                            AnimalId = 52,
                            Age = 2,
                            Breed = "norweigan",
                            Description = "cute and affectionate",
                            Name = "james",
                            Type = "cat"
                        },
                        new
                        {
                            AnimalId = 53,
                            Age = 17,
                            Breed = "beagle",
                            Description = "cute and affectionate",
                            Name = "bob",
                            Type = "dog"
                        },
                        new
                        {
                            AnimalId = 54,
                            Age = 9,
                            Breed = "siberian",
                            Description = "has a strong personality",
                            Name = "poppy",
                            Type = "cat"
                        },
                        new
                        {
                            AnimalId = 55,
                            Age = 9,
                            Breed = "lab",
                            Description = "needs a quiet home",
                            Name = "ames",
                            Type = "dog"
                        },
                        new
                        {
                            AnimalId = 56,
                            Age = 6,
                            Breed = "shorthair",
                            Description = "cute and affectionate",
                            Name = "ames",
                            Type = "cat"
                        },
                        new
                        {
                            AnimalId = 57,
                            Age = 6,
                            Breed = "husky",
                            Description = "needs a quiet home",
                            Name = "henry",
                            Type = "dog"
                        },
                        new
                        {
                            AnimalId = 58,
                            Age = 16,
                            Breed = "shorthair",
                            Description = "curious about the world",
                            Name = "eric",
                            Type = "cat"
                        },
                        new
                        {
                            AnimalId = 59,
                            Age = 6,
                            Breed = "german shepherd",
                            Description = "has a strong personality",
                            Name = "whiskers",
                            Type = "dog"
                        },
                        new
                        {
                            AnimalId = 60,
                            Age = 5,
                            Breed = "shorthair",
                            Description = "has a strong personality",
                            Name = "hailey",
                            Type = "cat"
                        },
                        new
                        {
                            AnimalId = 61,
                            Age = 14,
                            Breed = "poodle",
                            Description = "has a strong personality",
                            Name = "ames",
                            Type = "dog"
                        },
                        new
                        {
                            AnimalId = 62,
                            Age = 5,
                            Breed = "lab",
                            Description = "needs a quiet home",
                            Name = "james",
                            Type = "dog"
                        },
                        new
                        {
                            AnimalId = 63,
                            Age = 9,
                            Breed = "norweigan",
                            Description = "loves to run and play",
                            Name = "quin",
                            Type = "cat"
                        },
                        new
                        {
                            AnimalId = 64,
                            Age = 9,
                            Breed = "husky",
                            Description = "loves to run and play",
                            Name = "frederick",
                            Type = "dog"
                        },
                        new
                        {
                            AnimalId = 65,
                            Age = 16,
                            Breed = "siberian",
                            Description = "loves to run and play",
                            Name = "bob",
                            Type = "cat"
                        },
                        new
                        {
                            AnimalId = 66,
                            Age = 3,
                            Breed = "norweigan",
                            Description = "loves to run and play",
                            Name = "poppy",
                            Type = "cat"
                        },
                        new
                        {
                            AnimalId = 67,
                            Age = 9,
                            Breed = "lab",
                            Description = "needs a quiet home",
                            Name = "hailey",
                            Type = "dog"
                        },
                        new
                        {
                            AnimalId = 68,
                            Age = 8,
                            Breed = "husky",
                            Description = "cute and affectionate",
                            Name = "olive",
                            Type = "dog"
                        },
                        new
                        {
                            AnimalId = 69,
                            Age = 14,
                            Breed = "shorthair",
                            Description = "cute and affectionate",
                            Name = "bob",
                            Type = "cat"
                        },
                        new
                        {
                            AnimalId = 70,
                            Age = 10,
                            Breed = "beagle",
                            Description = "cute and affectionate",
                            Name = "claire",
                            Type = "dog"
                        },
                        new
                        {
                            AnimalId = 71,
                            Age = 4,
                            Breed = "siamese",
                            Description = "cute and affectionate",
                            Name = "olive",
                            Type = "cat"
                        },
                        new
                        {
                            AnimalId = 72,
                            Age = 9,
                            Breed = "norweigan",
                            Description = "loves to run and play",
                            Name = "frederick",
                            Type = "cat"
                        },
                        new
                        {
                            AnimalId = 73,
                            Age = 10,
                            Breed = "siberian",
                            Description = "loves to run and play",
                            Name = "claire",
                            Type = "cat"
                        },
                        new
                        {
                            AnimalId = 74,
                            Age = 11,
                            Breed = "shorthair",
                            Description = "curious about the world",
                            Name = "ames",
                            Type = "cat"
                        },
                        new
                        {
                            AnimalId = 75,
                            Age = 19,
                            Breed = "beagle",
                            Description = "curious about the world",
                            Name = "whiskers",
                            Type = "dog"
                        },
                        new
                        {
                            AnimalId = 76,
                            Age = 18,
                            Breed = "german shepherd",
                            Description = "cute and affectionate",
                            Name = "james",
                            Type = "dog"
                        },
                        new
                        {
                            AnimalId = 77,
                            Age = 18,
                            Breed = "german shepherd",
                            Description = "cute and affectionate",
                            Name = "hailey",
                            Type = "dog"
                        },
                        new
                        {
                            AnimalId = 78,
                            Age = 19,
                            Breed = "german shepherd",
                            Description = "loves to run and play",
                            Name = "henry",
                            Type = "dog"
                        },
                        new
                        {
                            AnimalId = 79,
                            Age = 7,
                            Breed = "siamese",
                            Description = "loves to run and play",
                            Name = "quin",
                            Type = "cat"
                        },
                        new
                        {
                            AnimalId = 80,
                            Age = 9,
                            Breed = "norweigan",
                            Description = "has a strong personality",
                            Name = "frederick",
                            Type = "cat"
                        },
                        new
                        {
                            AnimalId = 81,
                            Age = 17,
                            Breed = "beagle",
                            Description = "has a strong personality",
                            Name = "bob",
                            Type = "dog"
                        },
                        new
                        {
                            AnimalId = 82,
                            Age = 8,
                            Breed = "poodle",
                            Description = "cute and affectionate",
                            Name = "henry",
                            Type = "dog"
                        },
                        new
                        {
                            AnimalId = 83,
                            Age = 13,
                            Breed = "siberian",
                            Description = "needs a quiet home",
                            Name = "henry",
                            Type = "cat"
                        },
                        new
                        {
                            AnimalId = 84,
                            Age = 13,
                            Breed = "husky",
                            Description = "needs a quiet home",
                            Name = "henry",
                            Type = "dog"
                        },
                        new
                        {
                            AnimalId = 85,
                            Age = 7,
                            Breed = "munchkin",
                            Description = "curious about the world",
                            Name = "whiskers",
                            Type = "cat"
                        },
                        new
                        {
                            AnimalId = 86,
                            Age = 19,
                            Breed = "poodle",
                            Description = "needs a quiet home",
                            Name = "poppy",
                            Type = "dog"
                        },
                        new
                        {
                            AnimalId = 87,
                            Age = 7,
                            Breed = "siamese",
                            Description = "has a strong personality",
                            Name = "hal",
                            Type = "cat"
                        },
                        new
                        {
                            AnimalId = 88,
                            Age = 6,
                            Breed = "shorthair",
                            Description = "curious about the world",
                            Name = "yarin",
                            Type = "cat"
                        },
                        new
                        {
                            AnimalId = 89,
                            Age = 17,
                            Breed = "siamese",
                            Description = "curious about the world",
                            Name = "eric",
                            Type = "cat"
                        },
                        new
                        {
                            AnimalId = 90,
                            Age = 13,
                            Breed = "beagle",
                            Description = "cute and affectionate",
                            Name = "eric",
                            Type = "dog"
                        },
                        new
                        {
                            AnimalId = 91,
                            Age = 7,
                            Breed = "beagle",
                            Description = "needs a quiet home",
                            Name = "poppy",
                            Type = "dog"
                        },
                        new
                        {
                            AnimalId = 92,
                            Age = 2,
                            Breed = "shorthair",
                            Description = "cute and affectionate",
                            Name = "yarin",
                            Type = "cat"
                        },
                        new
                        {
                            AnimalId = 93,
                            Age = 7,
                            Breed = "shorthair",
                            Description = "curious about the world",
                            Name = "frederick",
                            Type = "cat"
                        },
                        new
                        {
                            AnimalId = 94,
                            Age = 7,
                            Breed = "munchkin",
                            Description = "has a strong personality",
                            Name = "thor",
                            Type = "cat"
                        },
                        new
                        {
                            AnimalId = 95,
                            Age = 11,
                            Breed = "shorthair",
                            Description = "has a strong personality",
                            Name = "quin",
                            Type = "cat"
                        },
                        new
                        {
                            AnimalId = 96,
                            Age = 14,
                            Breed = "munchkin",
                            Description = "has a strong personality",
                            Name = "yarin",
                            Type = "cat"
                        },
                        new
                        {
                            AnimalId = 97,
                            Age = 2,
                            Breed = "siberian",
                            Description = "curious about the world",
                            Name = "claire",
                            Type = "cat"
                        },
                        new
                        {
                            AnimalId = 98,
                            Age = 18,
                            Breed = "siberian",
                            Description = "curious about the world",
                            Name = "olive",
                            Type = "cat"
                        },
                        new
                        {
                            AnimalId = 99,
                            Age = 4,
                            Breed = "beagle",
                            Description = "curious about the world",
                            Name = "paws",
                            Type = "dog"
                        },
                        new
                        {
                            AnimalId = 100,
                            Age = 13,
                            Breed = "poodle",
                            Description = "cute and affectionate",
                            Name = "yarin",
                            Type = "dog"
                        });
                });

            modelBuilder.Entity("MyApi.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MyApi.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MyApi.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyApi.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MyApi.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
